name: CI-CD

on: 
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - uses: actions/checkout@v4.0.0
      - name: Run Gradle Test
        uses: actions/checkout@v4.0.0
      - name: Gradle Test
        run: |
          gradle clean test

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - uses: actions/checkout@v4.0.0
      - name: Docker Hub Auth
        uses: docker/login-action@v2.2.0
        with: 
          username: ${{secrets.DOCKERHUB_USR}}
          password: ${{secrets.DOCKERHUB_PWD}}
      - name: Building Docker Image
        uses: docker/build-push-action@v4.2.1
        with:
          context: .
          file: Dockerfile
          push: true
          tags:
            fernandodias08/wishlist-api:${{github.run_number}}
            fernandodias08/wishlist-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Defining the context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          images: fernandodias08/wishlist-api:${{github.run_number}}
          manifests:
            k8s/deployment.yaml


          
